apiVersion: v1
entries:
  forestsoft-helm-lamp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.909602535Z"
    description: A Helm chart for Kubernetes
    digest: 6ab6685c10f39cb91c18ca0b53fbdd3873245f71e875c53f227dcfe3d25fa0a4
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.3.3.tgz
    version: 1.3.3
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.907548689Z"
    description: A Helm chart for Kubernetes
    digest: cc29b8bf62eaae6c1073adaab6a14097caf5bec3c14792b157af5abb05338215
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.3.2.tgz
    version: 1.3.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.905360629Z"
    description: A Helm chart for Kubernetes
    digest: 55f112db9b7c1851f495681ee3ef7e921f59515c4befa00200bd3304539007aa
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.3.1.tgz
    version: 1.3.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.903278681Z"
    description: A Helm chart for Kubernetes
    digest: 9527c19c123ced772fd4035d795d6591d31b8268e16474c7ec9714b33c505492
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.889447482Z"
    description: A Helm chart for Kubernetes
    digest: ef473b878748ee1268956f2659b647e8a90ef0c1e9988eb91fba3881fed9ccf1
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.2.13.tgz
    version: 1.2.13
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.887191685Z"
    description: A Helm chart for Kubernetes
    digest: 5188b304f2544a5be1bff956c2f1ce05d9da957fe43e459d63ae421445fef474
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.2.12.tgz
    version: 1.2.12
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.88501628Z"
    description: A Helm chart for Kubernetes
    digest: ce8474da2f18d1570b228001221c0ec7ef56553aa12f2faaa1e85a135e255f42
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.2.11.tgz
    version: 1.2.11
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.882759404Z"
    description: A Helm chart for Kubernetes
    digest: 91b7ff9a7fe1ed90c145b5e6493f62169413793b9355fa327ad79153588a07c3
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.2.10.tgz
    version: 1.2.10
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.901022861Z"
    description: A Helm chart for Kubernetes
    digest: ae9f3bba899ed938697cb3c9628b668ba5293c2e1e50d9bef0bd46a7378a5645
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.2.9.tgz
    version: 1.2.9
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.898543424Z"
    description: A Helm chart for Kubernetes
    digest: ae803a85ea8df48bb05f8568c653bf994a0fcf6dd4becfb2477e5e5072f2e5ee
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.2.8.tgz
    version: 1.2.8
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.897256019Z"
    description: A Helm chart for Kubernetes
    digest: f49a8839a553384ad2cc003090e28820f9265962589145355f3eefbaeae0b5b8
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.2.7.tgz
    version: 1.2.7
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.895978571Z"
    description: A Helm chart for Kubernetes
    digest: 3028d81933b989ef1ce20a3066081ab3aeb279a3bb7fa5fef98612afa3459837
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.2.6.tgz
    version: 1.2.6
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.894630756Z"
    description: A Helm chart for Kubernetes
    digest: 8a2ea13a2ab62ddbbecff0ab824c631360655271f62243941ed860ed70842acb
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.2.5.tgz
    version: 1.2.5
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.893277804Z"
    description: A Helm chart for Kubernetes
    digest: 51d2521459129635562ba3132b9ebda8927b6c093eeb3126ca494f8b6d35d260
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.2.4.tgz
    version: 1.2.4
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.891905483Z"
    description: A Helm chart for Kubernetes
    digest: c62f5e44bf02560b0cfcd5d63f0ddb9f105cefc30a509e55d699847c946bf5fb
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.2.3.tgz
    version: 1.2.3
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.890666934Z"
    description: A Helm chart for Kubernetes
    digest: 51f95d4dba8667f8bb7ff8258c3c8bbd3c2bd001753a4b3f6f8b2b19902b07b9
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.2.2.tgz
    version: 1.2.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.880569568Z"
    description: A Helm chart for Kubernetes
    digest: 6026c6b4b11666422b0fc99edf7157e9288e43a1b95e202bb4b7caa4881533fa
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.2.1.tgz
    version: 1.2.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.878266196Z"
    description: A Helm chart for Kubernetes
    digest: b7ff42a93564882fae6e5d74a1ecc7084451107c021254647bf8bebd47edf7fc
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.874771248Z"
    description: A Helm chart for Kubernetes
    digest: 7295efb798158bf2d263b8f833290dcaff4882510b46951e8ab08d1a2f85966c
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.1.13.tgz
    version: 1.1.13
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.873702292Z"
    description: A Helm chart for Kubernetes
    digest: 9ec1dc7defc4e416fef9d63e2c12fbadb3e16efc8b84d6ac6aaf7e26d9b6f1ec
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.1.12.tgz
    version: 1.1.12
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.872610898Z"
    description: A Helm chart for Kubernetes
    digest: f98bf7d983c71db619c5a9755d5fcbccd6e8c951b62549572796dba483f1e81c
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.1.11.tgz
    version: 1.1.11
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.871421806Z"
    description: A Helm chart for Kubernetes
    digest: f5ab6f6fe39356d047e07f63afa89e908d96cec3a7195b611de3902f61021e30
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.1.10.tgz
    version: 1.1.10
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.875905634Z"
    description: A Helm chart for Kubernetes
    digest: 9f17d2f331eb99929d6a0d37929db841f420dd24579f8ec4f796a1bac43fea50
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.1.9.tgz
    version: 1.1.9
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-29T23:08:29.870297311Z"
    description: A Helm chart for Kubernetes
    digest: c8bc0c15ac3e44ef1f6436ed43de2591b3eee462aeadd9b0ec41fc675b1614e6
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.0.6.tgz
    version: 1.0.6
generated: "2022-01-29T23:08:29.868887172Z"
