apiVersion: v1
entries:
  forestsoft-helm-lamp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-10T21:25:51.826898917Z"
    description: A Helm chart for Kubernetes
    digest: 23364eae0f5aeb342374eb3be7e93b651932689fad9a946806b386dfe96e491b
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/charts/forestsoft-helm-lamp-1.0.6.tgz
    version: 1.0.6
generated: "2022-01-10T21:25:51.826057248Z"
