apiVersion: v1
entries:
  forestsoft-helm-lamp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-15T16:36:56.951552871Z"
    description: A Helm chart for Kubernetes
    digest: 9e0e4a12f0486056d4da168b334e46aa220f99e3cbc3f8e99820a3db7767ee7b
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.1.10.tgz
    version: 1.1.10
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-15T16:36:56.952766559Z"
    description: A Helm chart for Kubernetes
    digest: 9f17d2f331eb99929d6a0d37929db841f420dd24579f8ec4f796a1bac43fea50
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.1.9.tgz
    version: 1.1.9
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-01-15T16:36:56.950364437Z"
    description: A Helm chart for Kubernetes
    digest: c8bc0c15ac3e44ef1f6436ed43de2591b3eee462aeadd9b0ec41fc675b1614e6
    maintainers:
    - email: support@forestsoft.de
      name: Forestsoft GmbH
      url: https://forestsoft.de
    name: forestsoft-helm-lamp
    type: application
    urls:
    - https://Forestsoft-de.github.io/helm-charts/charts/forestsoft-helm-lamp-1.0.6.tgz
    version: 1.0.6
generated: "2022-01-15T16:36:56.948959208Z"
